[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry.dependencies]
python = "~3.11.0"
aiogram = "2.25.1"
python-dotenv = "1.0.0"
aiohttp = "3.8.6" 